.ORG 0000H
JMP MAIN

 
DELAY: 	MVI B,0FFH; SUBROUTINE FOR SHORT DELAY of 1"point"8ms
LOOP:	DCR B
	JNZ LOOP
	RET	

MAIN:	
	LXI SP ,0000H; INITIALIZING THE STACK POINTER
	PUSH PSW;SAVING ACCUMALATOR CONTENTS TO FFFFH
	MVI A,092H; CONTROL WORD FOR 8255 - P A&B=IP P C=OP
	OUT 03H; CONTROL REGISTER ADDRESS =03H
	MVI A,0C0H; CONTROL WORD FOR 0 O/P ON SOD
	SIM
	CALL LCD_INIT
	CALL DELAY
	CALL DATA1
	CALL DELAY1
	CALL DELAY1
	CALL DELAY1
	CALL DELAY1
	CALL DATA2
	CALL DELAY
	POP PSW
	HLT

LCD_INIT: MVI D, 033H; SENDING INITIALISATION COMMAND
	CALL COMMAND
	MVI D,032H; SENDING INITIALISATION COMMAND
	CALL COMMAND
	MVI D,028H; SENDING COMMAND TO INITIALIZE 4 BIT
	CALL COMMAND
	MVI D,006H; SENDING COMMAND TO INITIALIZE CURSOR
	CALL COMMAND
	MVI D,00FH; SEND COMMAND TO DISPLAY ON CURSOR BLINK
	CALL COMMAND
	MVI D,001H; SENDING COMMAND TO CLEAR DISPLAY
	CALL COMMAND
	MVI D,080H; COMMAND TO FORCE CURSOR FROM 1st LINE
	CALL COMMAND
	CALL DELAY
	CALL DELAY

	RET

DATA1: MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA	
	MVI D,048H; SENDING DATA "H"
	CALL DATA
	MVI D,065H; SENDING DATA "e"
	CALL DATA
	MVI D,061H; SENDING DATA "a"
	CALL DATA
	MVI D,06CH; SENDING DATA "l"
	CALL DATA
	MVI D,074H; SENDING DATA "t"
	CALL DATA
	MVI D,068H; SENDING DATA "h"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,04BH; SENDING DATA "K"
	CALL DATA
	MVI D,069H; SENDING DATA "i"
	CALL DATA
	MVI D,074H; SENDING DATA "t"
	CALL DATA
	MVI D,0C0H; COMMAND TO FORCE CURSOR FROM 2nd LINE
	CALL COMMAND
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,042H; SENDING DATA "B"
	CALL DATA
	MVI D,079H; SENDING DATA "y"
	CALL DATA
	CALL DELAY
	RET

DATA2:	MVI D,001H; SENDING COMMAND TO CLEAR DISPLAY
	CALL COMMAND
	MVI D,080H; COMMAND TO FORCE CURSOR FROM 1st LINE
	CALL COMMAND
	CALL DELAY
	CALL DELAY

	MVI D,041H; SENDING DATA "A"
	CALL DATA
	MVI D,064H; SENDING DATA "d"
	CALL DATA
	MVI D,068H; SENDING DATA "h"
	CALL DATA
	MVI D,069H; SENDING DATA "i"
	CALL DATA
	MVI D,072H; SENDING DATA "r"
	CALL DATA
	MVI D,061H; SENDING DATA "a"
	CALL DATA
	MVI D,06AH; SENDING DATA "j"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,043H; SENDING DATA "C"
	CALL DATA
	MVI D,068H; SENDING DATA "h"
	CALL DATA
	MVI D,061H; SENDING DATA "a"
	CALL DATA
	MVI D,06EH; SENDING DATA "n"
	CALL DATA
	MVI D,064H; SENDING DATA "d"
	CALL DATA
	MVI D,065H; SENDING DATA "e"
	CALL DATA
	MVI D,06CH; SENDING DATA "l"
	CALL DATA

	MVI D,0C0H; COMMAND TO FORCE CURSOR FROM 2nd LINE
	CALL COMMAND
	MVI D,031H; SENDING DATA "1"
	CALL DATA
	MVI D,032H; SENDING DATA "2"
	CALL DATA
	MVI D,045H; SENDING DATA "E"
	CALL DATA
	MVI D,043H; SENDING DATA "C"
	CALL DATA
	MVI D,031H; SENDING DATA "1"
	CALL DATA
	MVI D,034H; SENDING DATA "4"
	CALL DATA

	CALL DELAY1
	CALL DELAY1
	CALL DELAY1
	MVI D,001H; SENDING COMMAND TO CLEAR DISPLAY
	CALL COMMAND
	MVI D,080H; COMMAND TO FORCE CURSOR FROM 1st LINE
	CALL COMMAND
	CALL DELAY
	CALL DELAY


	MVI D,041H; SENDING DATA "A"
	CALL DATA
	MVI D,06AH; SENDING DATA "j"
	CALL DATA
	MVI D,061H; SENDING DATA "a"
	CALL DATA
	MVI D,079H; SENDING DATA "y"
	CALL DATA
	MVI D,020H; SENDING DATA "SPACE"
	CALL DATA
	MVI D,043H; SENDING DATA "C"
	CALL DATA
	MVI D,068H; SENDING DATA "h"
	CALL DATA
	MVI D,06FH; SENDING DATA "o"
	CALL DATA
	MVI D,075H; SENDING DATA "u"
	CALL DATA
	MVI D,064H; SENDING DATA "d"
	CALL DATA
	MVI D,068H; SENDING DATA "h"
	CALL DATA
	MVI D,061H; SENDING DATA "a"
	CALL DATA
	MVI D,072H; SENDING DATA "r"
	CALL DATA
	MVI D,079H; SENDING DATA "y"
	CALL DATA

	

	MVI D,0C0H; COMMAND TO FORCE CURSOR FROM 2nd LINE
	CALL COMMAND
	MVI D,031H; SENDING DATA "1"
	CALL DATA
	MVI D,035H; SENDING DATA "5"
	CALL DATA
	MVI D,045H; SENDING DATA "E"
	CALL DATA
	MVI D,043H; SENDING DATA "C"
	CALL DATA
	MVI D,031H; SENDING DATA "1"
	CALL DATA
	MVI D,034H; SENDING DATA "4"
	CALL DATA	
	CALL DELAY1
	CALL DELAY1
	CALL DELAY1
	MVI D,001H; SENDING COMMAND TO CLEAR DISPLAY
	CALL COMMAND

	CALL DELAY
	CALL DELAY

	RET

COMMAND: MOV A,D
	ANI 0F0H;MASKING UPPER 4 BITS AND RS=0 FOR COMMAND
	OUT 02H; PORT C ADDRESS OF 8255
	CALL DELAY
	ORI 02H; ENABLE HIGH AND RS LOW
	CALL DELAY
	OUT 02H
	CALL DELAY
	ANI 0F0H
	OUT 02H
	CALL DELAY
	MOV A,D
	RLC; SHIFTING THE 4 BITS
	RLC
	RLC
	RLC
	ANI 0F0H; MASKING LOWER 4 BITS
	OUT 02H
	CALL DELAY
	ORI 02H; ENABLE HIGH
	CALL DELAY
	OUT 02H
	CALL DELAY
	ANI 0F0H
	OUT 02H
	CALL DELAY
	RET


DATA: 	MOV A,D
	ANI 0F1H; MAKING RS=1 FOR DATA REGISTER
	OUT 02H; PORT C ADDRESS OF 8255
	CALL DELAY
	ORI 03H; ENABLE HIGH AND RS HIGH
	CALL DELAY
	OUT 02H
	CALL DELAY
	ANI 0F1H
	OUT 02H
	CALL DELAY
	MOV A,D
	RLC; SHIFTING THE 4 BITS
	RLC
	RLC
	RLC
	ANI 0F1H
	OUT 02H
	CALL DELAY
	ORI 03H; ENABLE HIGH
	CALL DELAY
	OUT 02H
	CALL DELAY
	ANI 0F1H
	OUT 02H
	CALL DELAY
	RET

DELAY1:	LXI H, 0FFFFH
LOOP1:	DCX H
	MOV A,L
	ORA H
	JNZ LOOP1 
	RET